<a href="https://colab.research.google.com/github/19PA1A0271/AI-lab/blob/master/Experiment_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 1) Experiment 1:Numpy

1)Different ways to creat Numpy arrays

In [ ]:
 
import numpy as np
a = np.array([2,6,9]) 
print (a)

[2 6 9]


In [ ]:
 
a = np.array([[1, 2], [3, 4]]) 
print (a)

[[1 2]
 [3 4]]


 2)Add,remove,modify elements in an array

In [ ]:
 
newArray = np.append(a,[44,36,48])
print(newArray)

[ 1  2  3  4 44 36 48]


In [ ]:
 
import numpy as np
l=np.array([4,6,9,3,7])
l=np.delete(l,4)
print(l)

[4 6 9 3]


In [ ]:
 
b=np.array([9,6,4,1,8,5])
b[b<2]=-1
print(b)

[ 9  6  4 -1  8  5]


3) Arthematic operations on Numpy arrays

In [ ]:
import numpy as np
v=np.random.random((8,8))
n=np.random.random((8,8))
sum=np.add(v,n)
diff=np.subtract(v,n)
prod=np.multiply(v,n)
quo=np.divide(v,n)
mod=np.mod(v,n)
pow=np.power(v,n)
print(sum)
print(diff)
print(prod) 
Print(quo) 
Print(mod) 
Print(pow)

[[1.63646426 0.36328055 1.2276298  0.76085629 0.79723517 1.1350244
  0.35646538 0.65359005]
 [0.60865251 1.29038635 0.57832295 1.1418653  0.56060486 1.84366163
  1.21627999 0.78817739]
 [1.23229846 1.28827892 1.69346736 0.85750053 0.91694554 0.89260569
  1.18593978 0.55371241]
 [0.79595041 0.83402977 0.88722095 1.00169442 1.43191357 0.9192413
  1.13924996 1.18147081]
 [0.82256796 1.32754943 1.4556449  1.22331281 1.12286999 1.09226746
  1.16431334 0.26347468]
 [1.47626722 0.52782955 1.85391436 1.37426871 0.95229916 1.1349815
  1.1541851  1.34817772]
 [1.78721755 1.05065817 1.18823031 0.7183024  1.103255   0.73587142
  1.17689056 1.01707392]
 [0.34139047 1.25587283 0.58480152 0.86114441 0.1711296  0.59678215
  1.87501764 0.86321424]]
[[-0.36147835  0.18543522 -0.2382089  -0.33300048 -0.57635205  0.21343219
  -0.19055567  0.29546835]
 [ 0.10261148 -0.02370755  0.11089849  0.27924698  0.16645063  0.12880958
   0.47732787 -0.69839715]
 [-0.20206638 -0.37463184  0.26178766  0.33222392  0.493

 4) Slicing and iterating of Numpy arrays

Slicing

In [ ]:
 
import numpy as np
arr=np.array([4,5,6,8,9,7])
print(arr[2:6])

[6 8 9 7]


Iterating

In [ ]:
for i in arr: 
  print(i)

4
5
6
8
9
7


5) Matrix operation on Numpy arrays

In [ ]:
 
import numpy as np
v=np.array([[5,9],[4,3]])
i=np.array([[2,16],[1,12]])
print(np.add(v,i))
print(np.subtract(v,i))
print(np.divide(v,i))

[[ 7 25]
 [ 5 15]]
[[ 3 -7]
 [ 3 -9]]
[[2.5    0.5625]
 [4.     0.25  ]]
